name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd used_car_mlops
        pip install -r requirements.txt

    - name: Run training script
      run: |
        cd used_car_mlops
        python src/train.py

    - name: Build Docker Image
      run: |
        cd used_car_mlops
        docker build -t used-car-mlops .

    - name: Deploy to Kubernetes
      run: |
        echo "kubectl apply -f k8s-deployment.yaml"
